version: '3'
services:

  nodeserver:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports: 
      - 4000:4000
    depends_on:
      - mongoserver
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app

  mongoserver:
    image: mongo:latest
    ports: 
      - "27017:27017"

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports: 
      - "8000:80"
  